// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

/// Actions OTA 升级状态枚举 | Actions OTA upgrade state enum
typedef NS_ENUM(NSUInteger, ActionsOTAState) {
  ActionsOTAStatePrepare = 0,
  ActionsOTAStateUploading = 1,
  ActionsOTAStateCompleted = 2,
  ActionsOTAStateFailed = 3,
  ActionsOTAStateCancelled = 4,
};

/// Wrapper for ActionsOTAState to allow for nullability.
@interface ActionsOTAStateBox : NSObject
@property(nonatomic, assign) ActionsOTAState value;
- (instancetype)initWithValue:(ActionsOTAState)value;
@end


/// The codec used by ApiActionsHost.
NSObject<FlutterMessageCodec> *ApiActionsHostGetCodec(void);

/// Flutter 调用原生的 API | API for Flutter to call native
@protocol ApiActionsHost
/// 开始 Actions OTA 升级 | Start Actions OTA upgrade
/// deviceIdentifier: iOS 传 UUID，Android 传 MAC 地址 | iOS passes UUID, Android passes MAC address
/// filePath: 固件文件路径 | Firmware file path
- (void)startOTADeviceIdentifier:(NSString *)deviceIdentifier filePath:(NSString *)filePath error:(FlutterError *_Nullable *_Nonnull)error;
/// 停止 Actions OTA 升级 | Stop Actions OTA upgrade
- (void)stopOTAWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ApiActionsHostSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ApiActionsHost> *_Nullable api);

/// The codec used by ApiActionsFlutter.
NSObject<FlutterMessageCodec> *ApiActionsFlutterGetCodec(void);

/// 原生调用 Flutter 的 API | API for native to call Flutter
@interface ApiActionsFlutter : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
/// 升级状态变更 | Upgrade state changed
/// state: 当前状态 | Current state
/// errorMessage: 失败时的错误信息（非失败状态传空字符串） | Error message on failure
- (void)onOTAStateChangedState:(ActionsOTAState)state errorMessage:(NSString *)errorMessage completion:(void (^)(FlutterError *_Nullable))completion;
/// 升级进度变更 | Upgrade progress changed
/// progress: 进度值 (0 ~ 100) | Progress value (0 ~ 100)
/// message: 附加信息 | Extra message
- (void)onOTAProgressProgress:(NSNumber *)progress message:(NSString *)message completion:(void (^)(FlutterError *_Nullable))completion;
/// 日志输出 | Log output
- (void)logLogMsg:(NSString *)logMsg completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
